FROM postgres:9.6.3-alpine

RUN mkdir -p /code
WORKDIR /code
ADD . /code

RUN apk update && apk add nodejs
RUN npm install --global yarn
RUN yarn global add grunt-cli knex
RUN yarn install

EXPOSE 5432